### ISSUE TITLE
F-Droid submission

### ISSUE THREAD

**Issue by Primokorn** [sovworks/edslite#1]
Hi,
I suggested your Android app to F-Droid team: https://gitlab.com/fdroid/rfp/issues/316#note_38057080
Could you use GPLv2+ instead of GPLv2?

Let us know if you don't want to see your app in this repository.
Thank you.

**Comment by theScrabi** [comment]
@Primokorn but gplv2 iplies that in can be gplv2+ as well doesn't it? I's just not the official string.

**Comment by Primokorn** [comment]
@theScrabi No, it doesn't. GPLv2 will always be GPLv2 unless you put the `+` sign.
Anyway yt's a request from F-Droid team so the app will never been adeed as long as the license doesn't change.

**Comment by theScrabi** [comment]
fdroid PR is out:
https://gitlab.com/fdroid/fdroiddata/merge_requests/3426
